#!/usr/bin/env bash
set -Eeuo pipefail

# https://github.com/nextcloud/all-in-one#how-to-run-occ-commands

docker exec --user www-data \
    --interactive --tty \
    nextcloud-aio-nextcloud php occ "${@}"
